server_name: Dynamite
server_ip: 0.0.0.0
server_port: 25565
view_distance: 16
simulation_distance: 16
motd: A Dynamite Minecraft Server
icon:
  path: server-icon.png
  enable: true
whitelist:
  enforce: true
  enable: false
gamemode: creative
hardcore: false
max_players: 20
online_mode: false
tablist:
  header: []
  footer: []
chat:
  format: '%player_prefix%§7%player%§8: §f%message%'
  colors: true
  enable: true
messages:
  not_in_whitelist: You are not whitelisted.
  banned: You are banned from this server.
  server_full: The server is full.
  already_playing: You are already playing on this server with a different client.
  player_join: §e%player% has joined the game
  player_leave: §e%player% has left the game
  unknown_command: §cUnknown command. Please use '/help' for a list of commands.
  protocol_new: Your protocol is too new!
  protocol_old: Your protocol is too old!
  insufficient_permissions: §cYou aren't permitted to use this command.
  reload_complete: §aReload complete.
  server_closed: Server closed.
  online_mode: The server is in online mode.