name: Build GoCraft

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.20.x']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libx11-dev xorg-dev libwayland-dev libxkbcommon-dev bc
        if: ${{ runner.os == 'Linux' }}
      - name: Build
        run: go build -v ./...
      - name: Upload Go build results linux
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'Linux' }}
        with:
          name: GoCraft-Linux
          path: gocraft
      - name: Upload Go build results windows
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'Windows' }}
        with:
          name: GoCraft-Windows
          path: gocraft.exe
      - name: Upload Go build results windows
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'macOS' }}
        with:
          name: GoCraft-Windows
          path: gocraft.exe